export const ENV = {
  GEMINI_API_KEY: 'GEMINI_API_KEY',
  GOOGLE_TTS_API_KEY: 'GOOGLE_TTS_API_KEY',
  GOOGLE_TTS_SERVICE_ACCOUNT_JSON: 'GOOGLE_TTS_SERVICE_ACCOUNT_JSON',
  GOOGLE_TTS_SERVICE_ACCOUNT_FILE: 'GOOGLE_TTS_SERVICE_ACCOUNT_FILE',
  ELEVENLABS_API_KEY: 'ELEVENLABS_API_KEY',
  ELEVENLABS_MODEL_ID: 'ELEVENLABS_MODEL_ID',
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_RAW_BUCKET: 'AWS_S3_RAW_BUCKET',
  AWS_S3_OUTPUT_BUCKET: 'AWS_S3_OUTPUT_BUCKET',
  AWS_PRESIGN_GET_TTL_SEC: 'AWS_PRESIGN_GET_TTL_SEC',
  AWS_PRESIGN_PUT_TTL_SEC: 'AWS_PRESIGN_PUT_TTL_SEC',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_ADMIN_EXPIRES_IN: 'JWT_ADMIN_EXPIRES_IN',
  JWT_REFRESH_ENABLED: 'JWT_REFRESH_ENABLED',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_REDIRECT_URI: 'GOOGLE_REDIRECT_URI',
  NODE_ENVIRONMENT: 'node_environment',
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
  BULL_BOARD_USER: 'BULL_BOARD_USER',
  BULL_BOARD_PASS: 'BULL_BOARD_PASS',
};

export const { SWAGGER_PASSWORD = '' } = process.env || {};

export const NODE_ENVIRONMENT =
  process.env[ENV.NODE_ENVIRONMENT] ?? process.env.NODE_ENV ?? 'development';
